"""
Workflow Visualizer - 工作流可视化导出器
支持Mermaid、ASCII、JSON等格式
"""
from __future__ import annotations

import json
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
import datetime

logger = logging.getLogger(__name__)


class ExportFormat(str, Enum):
    MERMAID = "mermaid"
    MERMAID_FLOWCHART = "mermaid_flowchart"
    MERMAID_SEQUENCE = "mermaid_sequence"
    ASCII = "ascii"
    JSON = "json"
    HTML = "html"


@dataclass
class NodeData:
    id: str
    label: str
    node_type: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class EdgeData:
    source: str
    target: str
    label: Optional[str] = None
    edge_type: str = "default"


@dataclass
class WorkflowGraph:
    name: str
    nodes: List[NodeData] = field(default_factory=list)
    edges: List[EdgeData] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


class WorkflowExporter(ABC):
    @abstractmethod
    def export(self, graph: WorkflowGraph) -> str:
        pass


class MermaidExporter(WorkflowExporter):
    def __init__(self, flowchart_type: str = "TD"):
        self.flowchart_type = flowchart_type

    def export(self, graph: WorkflowGraph) -> str:
        lines = [f"%% {graph.name} - Generated by OpenTaiji"]
        lines.append(f"flowchart {self.flowchart_type}")
        for node in graph.nodes:
            if node.node_type == "end":
                lines.append(f"    {self._safe_id(node.id)}(({node.label}))")
            elif node.node_type == "condition":
                lines.append(f"    {self._safe_id(node.id)}{{{node.label}}}")
            elif node.node_type == "parallel":
                lines.append(f"    {self._safe_id(node.id)}>[[{node.label}]]")
            else:
                lines.append(f"    {self._safe_id(node.id)}[{node.label}]")
        for edge in graph.edges:
            source = self._safe_id(edge.source)
            target = self._safe_id(edge.target)
            if edge.label:
                lines.append(f"    {source} -->|\"{edge.label}\"| {target}")
            else:
                lines.append(f"    {source} --> {target}")
        return "\n".join(lines)

    def _safe_id(self, node_id: str) -> str:
        return node_id.replace(" ", "_").replace("-", "_")


class MermaidSequenceExporter(WorkflowExporter):
    def export(self, graph: WorkflowGraph) -> str:
        lines = [
            "%% Sequence Diagram",
            "sequenceDiagram",
        ]
        participants = {node.id: node.label for node in graph.nodes}
        for participant_id, label in participants.items():
            lines.append(f"    participant {participant_id} as {label}")
        for edge in graph.edges:
            if edge.label:
                lines.append(f"    {edge.source}->>+{edge.target}: {edge.label}")
            else:
                lines.append(f"    {edge.source}->>+{edge.target}:")
        return "\n".join(lines)


class ASCIIExporter(WorkflowExporter):
    def export(self, graph: WorkflowGraph) -> str:
        lines = [
            f"{graph.name}",
            "=" * len(graph.name),
            f"Generated: {datetime.datetime.now().isoformat()}",
            "",
            f"Nodes ({len(graph.nodes)}):",
            "-" * 40,
        ]
        for node in graph.nodes:
            marker = ""
            if node.node_type == "entry":
                marker = " [ENTRY]"
            elif node.node_type == "end":
                marker = " [END]"
            lines.append(f"  • {node.id}: {node.label} ({node.node_type}){marker}")
        lines.extend(["", f"Edges ({len(graph.edges)}):", "-" * 40])
        for edge in graph.edges:
            if edge.label:
                lines.append(f"  {edge.source} ──[{edge.label}]──> {edge.target}")
            else:
                lines.append(f"  {edge.source} ─────────────> {edge.target}")
        if graph.metadata:
            lines.extend(["", "Metadata:", "-" * 40])
            for key, value in graph.metadata.items():
                lines.append(f"  {key}: {value}")
        return "\n".join(lines)


class JSONExporter(WorkflowExporter):
    def __init__(self, pretty: bool = True):
        self.pretty = pretty

    def export(self, graph: WorkflowGraph) -> str:
        data = {
            "name": graph.name,
            "generated_at": datetime.datetime.now().isoformat(),
            "generator": "OpenTaiji 2.0",
            "nodes": [
                {
                    "id": node.id,
                    "label": node.label,
                    "type": node.node_type,
                    **node.metadata,
                }
                for node in graph.nodes
            ],
            "edges": [
                {
                    "source": edge.source,
                    "target": edge.target,
                    "label": edge.label,
                    "type": edge.edge_type,
                }
                for edge in graph.edges
            ],
            "metadata": graph.metadata,
        }
        if self.pretty:
            return json.dumps(data, ensure_ascii=False, indent=2)
        return json.dumps(data, ensure_ascii=False)


class HTMLExporter(WorkflowExporter):
    def export(self, graph: WorkflowGraph) -> str:
        mermaid = MermaidExporter().export(graph)
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{graph.name} - OpenTaiji Workflow</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <style>
        body {{ font-family: system-ui, sans-serif; margin: 2rem; }}
        .mermaid {{ background: #f8f9fa; padding: 1rem; border-radius: 8px; }}
    </style>
</head>
<body>
    <h1>{graph.name}</h1>
    <div class="mermaid">
{mermaid}
    </div>
    <script>
        mermaid.initialize({{ startOnLoad: true }});
    </script>
</body>
</html>"""
        return html


class WorkflowExporterFactory:
    _exporters = {
        ExportFormat.MERMAID: MermaidExporter,
        ExportFormat.MERMAID_FLOWCHART: MermaidExporter,
        ExportFormat.MERMAID_SEQUENCE: MermaidSequenceExporter,
        ExportFormat.ASCII: ASCIIExporter,
        ExportFormat.JSON: JSONExporter,
        ExportFormat.HTML: HTMLExporter,
    }

    @classmethod
    def create(cls, format: ExportFormat, **kwargs) -> WorkflowExporter:
        exporter_class = cls._exporters.get(format)
        if not exporter_class:
            raise ValueError(f"Unknown format: {format}")
        return exporter_class(**kwargs)

    @classmethod
    def export(
        cls,
        graph: WorkflowGraph,
        format: ExportFormat,
        **kwargs,
    ) -> str:
        exporter = cls.create(format, **kwargs)
        return exporter.export(graph)
