apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opentaiji
  namespace: opentaiji
  labels:
    app.kubernetes.io/name: opentaiji
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: opentaiji
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to: []
      ports:
        - protocol: TCP
          port: 443
    - to: []
      ports:
        - protocol: TCP
          port: 80
