apiVersion: v1
kind: Service
metadata:
  name: opentaiji
  namespace: opentaiji
  labels:
    app.kubernetes.io/name: opentaiji
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: opentaiji
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: opentaiji-headless
  namespace: opentaiji
  labels:
    app.kubernetes.io/name: opentaiji
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: opentaiji
    app.kubernetes.io/component: api
